### ISSUE TITLE
Can I pass multiple parameters to the thpool_add_work() method?

### ISSUE THREAD

**Issue by HatakeKakaxi** [Pithikos/C-Thread-Pool#107]
It seems that the function thpool_add_work() only accept a single parameter for function_p. Can I pass multiple parameters to it?

**Comment by trapexit** [comment]
That is a typical pattern. There isn't a great way to do otherwise. It's not like C has variadic template args which could be used to automate the creation of such things. You could use variadic arguments but that has its downsides. Providing a single void pointer interface allows the caller to do whatever they want and keeps things simple. You can simply wrap your args in a struct and pass that in and create simple function wrappers to take separate arguments and put them into the struct before calling add work.
