### ISSUE TITLE
Why don't threadpool lock num_threads_working?

### ISSUE THREAD

**Issue by cs-moushuai** [Pithikos/C-Thread-Pool#123]
Original
```c
int thpool_num_threads_working(thpool_* thpool_p) {
	return thpool_p->num_threads_working;
}
```

What I expect
```c
int thpool_num_threads_working(thpool_* thpool_p) {      
	pthread_mutex_lock(&thpool_p->thcount_lock);
	int num = thpool_p->num_threads_working
        pthread_mutex_unlock(&thpool_p->thcount_lock);

	return num;
}
```

**Comment by Pithikos** [comment]
Internally `num_threads_working` is always locked both when editing or reading. The exposure of it outside the threadpool (via `thpool_num_threads_working`) is just as an extra for the user.

The arguing is that there's no reason to lock it, since even if the value is not 100% accurate always, it eventually is and can't think a reason it would create any serious issue. But feel free to correct my if you figure out such a case
