### ISSUE TITLE
Why polling in thpool_wait?

### ISSUE THREAD

**Issue by dweymouth** [Pithikos/C-Thread-Pool#23]
The exponential polling is a clever way to not waste CPU too much, but why not wait on a condition var (e.g. jobs_empty) that's essentially the opposite of has_jobs? That would eliminate the need for polling at all.

**Comment by Pithikos** [comment]
Drew you are probably right. At the moment I refactored the code I just didn't think about it since I was more focused in adding the synchronisation calls `thpool_pause` and `thpool_resume` which did make my head ache quite a bit to be frank. You are right and probably this should be taken into consideration for future refactorization.

**Comment by dweymouth** [comment]
If I find the time, I'll work on this refactoring in a fork and send you a pull request :)

**Comment by Pithikos** [comment]
That sounds great. Keep in mind that `has_jobs` is a binary semaphore and if I remember correctly - the only one in the code. So feel free to remove all binary semaphore stuff to make the codebase more lightweight. Cheers!

**Comment by Pithikos** [comment]
Resolved @860303e
