### ISSUE TITLE
support win32

### ISSUE THREAD

**Issue by boxerab** [Pithikos/C-Thread-Pool#29]
First of all, thanks so much for making this project available - there is nothing quite like this out there for c language.

Have you thought about supporting windows ?  I would be happy to work on this, as I need it for one of my projects.  

Cheers,
Aaron

**Comment by Pithikos** [comment]
Hi boxerab,

I didn't think of supporting windows since I have used this only on Linux. Anyhow if you  implement this for Windows I can merge it after review. The main thing I want to avoid is having too many windows specific things mixed in the code. But if you manage to solve it in an elegant way then I would be happy if you implement it :) Oh yeah, and as long as the API remains platform agnostic!

**Comment by boxerab** [comment]
Thanks! I've decided to move my library to C++11, so I can just use the threading baked into C++.
Closing.
